<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>

<p align="right" class="MsoNormal" style="margin: 0cm 50px 0pt; text-align: right; mso-outline-level: 1;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">${doc_code} <o:p></o:p></font></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 26pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 26pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 26pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 26pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; mso-outline-level: 1;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		北</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		京</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		市</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		涉</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		案</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		财</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		物</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>

<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		价</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		格</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		认</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		定</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		结</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		论</span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"> &nbsp;&nbsp;</font></span></b>
	<b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 28pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
		书</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 28pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; mso-outline-level: 1;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 16pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">北京市价格认证中心</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 16pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
</br></br>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 16pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
		<span style="display:none">:dsysdate</span><o:p></o:p></font></span></b></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US"><o:p><font color="#000000" face="Times New Roman" size="3">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p align="right" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: right; mso-outline-level: 1;">
	<br clear="all" style="page-break-before: always;" />
	&nbsp;</p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="font-family: 宋体; font-size: 24pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">北京市涉案财物价格认定结论书</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 7.5pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 12pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 12pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; mso-outline-level: 1;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${doc_code}<o:p></o:p></font></span></b></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 12pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>

<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 12pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></b></font></span></b></font></span></b></p>

<img src="/pe/images/4line.jpg" width="617px" height="26px"/>


<p align="right" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: right; mso-outline-level: 1;">
	&nbsp;</p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; layout-grid-mode: char; mso-layout-grid-align: none; mso-line-height-alt: 5.0pt;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="font-size: 6.5pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${p_name}</font></span></b><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">：</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-char-indent-count: 2.0; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">根据你单位出具的价格认定协助书，遵循依法、公正、科学、合理、保密的原则，按照规定的程序，我单位对</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${p_context}</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">进行了价格认定。现将有关认定情况综述如下：</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	一、价格认定标的</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 29.25pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">本次价格认定标的：</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${p_context}${obj_name}<o:p></o:p></font></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 29.25pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><o:p></o:p></font></font></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	二、价格认定目的</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">确定价格认定标的在价格认定基准日的市场价格，为你单位<span style="mso-bidi-font-weight: bold;">办理</span>案件提供价格依据。</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	三、价格认定基准日</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">本次价格认定基准日：</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${basedate}</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">。</span><span lang="EN-US" style="color: blue; line-height: 150%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 8pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	四、价格定义</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">价格认定结论所指价格是：认定标的在价格认定基准日，采用公开市场价值标准确定的市场价格。</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	五、价格认定依据</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>

<#list gists as g>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-char-indent-count: 2.0; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman">
	${g}<o:p></o:p></font></font></span></font></span></b></font></span></b></p>
</#list>	
	
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	六、价格认定方法</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	${pmethod}<o:p></o:p></font></font></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">七、价格认定过程</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-char-indent-count: 2.0; mso-layout-grid-align: none;">
	<span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman">
	${pprocess}<o:p></o:p></font></font></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 9pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	八、价格认定结论</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	认定标的市场价格：人民币${mprice}</span>
	
	</b></font></span></b></p>
<#list mPrice2List as mPrice2>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-char-indent-count: 2.0; mso-layout-grid-align: none;">
	<span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman">
	${mPrice2}<o:p></o:p></font></font></span></p>
</#list>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span><o:p></o:p></font></font></span></b></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30.1pt; layout-grid-mode: char; mso-char-indent-count: 2.0; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	九、价格认定限定条件</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	1</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、提出方提供资料客观、真实、准确；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	十、声明</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	1</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、价格认定结论受结论书中已说明的限定条件限制；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	2</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、本次价格认定依据提出方提供的有关资料，提出方对其提供资料的真实性、合法性、可靠性负法律责任，价格认定方只对提出方提供材料基础上所作出的认定结论负相应责任；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	3</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、价格认定方依照《北京市价格鉴定工作规范》进行分析，形成意见和结论，撰写本价格认定结论；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	4</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、价格认定机构、认定人员与价格认定标的及有关当事人没有利害关系；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	5</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、价格认定结论只对本次提出有效，不作它用。未经价格认定机构允许，不得向提出方和价格认定审查及使用者以外的单位和个人提供，结论书的全部或部分内容不得发表于任何公开媒体上；</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	6</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">、提出方如对本结论有异议，可于结论书送达之日起</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">15</font></span><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">日内向原价格认定机构提出重新认定，或者向国家发展改革委价格认证中心提出复核裁定。</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	十一、作业日期</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font color="#000000"><font face="Times New Roman">
	<span style="display:none">:sysdate</span><o:p></o:p></font></font></span></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	十二、价格认定小组人员</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p><font color="#000000" face="Times New Roman">&nbsp;</font></o:p></span></font></span></b></font></span></b></p>
<br/>
<br/>
<br/>
<#list personList as person>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman">
	${person}<o:p></o:p></font></font></span></font></span></b></font></span></b></p>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
</#list>
<br/>
<br/>
<br/>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">
	十三、附件</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>

<p class="MsoNormal" style="margin: 0cm 0cm 0pt; line-height: 150%; text-indent: 30pt; layout-grid-mode: char; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">北京市涉案财产价格鉴定机构资质证书。</span><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></font></font></span></b></font></span></b></p>

<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 150%; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><font color="#000000"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><span style="mso-spacerun: yes;"><font face="Times New Roman">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font></span></span></b><b style="mso-bidi-font-weight: normal;"><span style="line-height: 200%; font-family: 宋体; font-size: 15pt; mso-bidi-font-size: 10.0pt; mso-ascii-font-family: &quot;Times New Roman&quot;; mso-hansi-font-family: &quot;Times New Roman&quot;;">北京市价格认证中心</span></b><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="line-height: 200%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><o:p></o:p></span></b></font></font></span></b></font></span></b></p>
<p align="center" class="MsoNormal" style="margin: 0cm 0cm 0pt; text-align: center; line-height: 150%; layout-grid-mode: char; mso-outline-level: 1; mso-layout-grid-align: none;">
	<b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; font-size: 14pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><b style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="color: blue; line-height: 150%; font-size: 15pt; mso-bidi-font-size: 10.0pt;"><font face="Times New Roman"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
	<span style="display:none">:dsysdate</span><o:p></o:p></font></span></b></font></span></b></font></span></b></p>
<p>
	&nbsp;</p>
